name: Pre-commit auto-update

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  pre-commit-autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "{{ cookiecutter.python_version }}"
      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
          key: {{"${{"}} runner.os {{"}}"}}-{{ cookiecutter.python_version }}-{{"${{"}} hashFiles('**/.pre-commit-config.yaml') {{"}}"}}
      - uses: browniebroke/pre-commit-autoupdate-action@main
      - uses: peter-evans/create-pull-request@v5
        if: always()
        with:
          token: {{"${{"}} secrets.GITHUB_TOKEN {{"}}"}}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
