{% if cookiecutter.is_library == "yes" %}
name: Upload Python Package

env:
  PYTHON_VERSION_FOR_PACKAGING: "{{ cookiecutter.python_version }}"
  POETRY_VERSION: "1.6"


on:
  push:
    tags:
      - "*"

jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "{{ '${{ env.PYTHON_VERSION_FOR_PACKAGING }}' }}"
      - name: Cache Pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: "{{ '${{ runner.os }}' }}"-"{{ '${{ env.PYTHON_VERSION_FOR_BUMPING }}' }}"-"{{ '${{ hashFiles(\'**/poetry.lock\') }}' }}"
      - run: pip install poetry~="{{ '${{ env.POETRY_VERSION }}' }}"
      - run: poetry build
      # From https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi-and-testpypi
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: "{{ '${{ secrets.PYPI_API_TOKEN }}' }}"
{% endif %}
